---
detectors:
  # Flog will handle this.
  TooManyStatements:
    enabled: false
  TooManyConstants:
    enabled: false
  #
  UncommunicativeVariableName:
    accept:
      - e
  IrresponsibleModule:
    exclude:
     - Error
