---
detectors:
  # Flog will handle this.
  TooManyStatements:
    enabled: false
  TooManyConstants:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  UncommunicativeVariableName:
    enabled: false
  UtilityFunction:
    public_methods_only: true
  FeatureEnvy:
    enabled: false
  IrresponsibleModule:
    exclude:
     - Error
